var level2 = { "height":15,
 "layers":[
        {
         "compression":"zlib",
         "data":"eJxjYMAPNhKQh4EYKB1HpPpRQFswfaAdMMTAVDT+FCqbP5PK5o0CysBQjo+lA+2AQQKqoXQslK5BkttNZ7cMBBgt4wcXGMplykgCs4iUH8w0AKoNFX4=",
         "encoding":"base64",
         "height":15,
         "name":"Background",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":50,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eJxjYBh4UDXQDqAyyIXS+VQ2Lw+Nppb5QxGghwm1wqKdSuaMAsrAUijdBqUXY1ETA6VjoXQcTV00skEtlIaFdd1AOWQQgGooDQuLmoFyyCgYUmAgyqu1aPRgA7jaNoTqdWq0sbJx0EMBAACbWhEl",
         "encoding":"base64",
         "height":15,
         "name":"Platforms",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":50,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eJxjYBgFo2Dogs0D7YBRgAI20dGu0bgnDOgZH\/S0a6iC0fgYXGA0jEbBUAQAvbUFkw==",
         "encoding":"base64",
         "height":15,
         "name":"Ladders",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":50,
         "x":0,
         "y":0
        }],
 "nextobjectid":4,
 "orientation":"orthogonal",
 "properties":
    {

    },
 "renderorder":"right-down",
 "tileheight":35,
 "tilesets":[
        {
         "firstgid":1,
         "image":"tileset.png",
         "imageheight":1024,
         "imagewidth":1024,
         "margin":2,
         "name":"Platformer",
         "properties":
            {

            },
         "spacing":2,
         "tilecount":196,
         "tileheight":70,
         "tilewidth":70
        }],
 "tilewidth":35,
 "version":1,
 "width":50
}